### ISSUE TITLE
Standardize code formatting?

### ISSUE THREAD

**Issue by bdpedigo** [CAVEconnectome/CAVEclient#169]
Spinning off conversation from https://github.com/CAVEconnectome/CAVEclient/pull/167

I propose using ruff as an autoformatter and enforcing this in the tests.

Upside is fewer formatting-based diffs on PRs and cleaner looking code IMO.

Downside is an annoyance when tests fail just because you didn't run autoformatting. I think this can be alleviated by using pre commit hooks or just setting up code editor to run it automatically on save. 

cc: @ceesem

**Comment by bdpedigo** [comment]
yeah i meant a github action that would check with ruff

**Comment by ceesem** [comment]
I just mean I'd rather it just do the formatting than test agains it.

**Comment by bdpedigo** [comment]
Closed by #170
