### ISSUE TITLE
Add a `timestamp` property to `ChunkedGraphClient`s

### ISSUE THREAD

**Issue by bdpedigo** [CAVEconnectome/CAVEclient#191]
Much like `MaterializationClient` has a `version` property with a setter, it seems like it would make sense to do the same for `timestamp` in chunkedgraph

This would basically just expose the existing `_default_timestamp` attribute, which is currently private
https://github.com/CAVEconnectome/CAVEclient/blob/ed0b1aecf3a2083be1b8bc6a97bd9c97ab42b4ee/caveclient/chunkedgraph.py#L189

I think it'd also make sense to update the documentation for methods that use timestamp to say this is what happens when `timestamp=None`
https://github.com/CAVEconnectome/CAVEclient/blob/ed0b1aecf3a2083be1b8bc6a97bd9c97ab42b4ee/caveclient/chunkedgraph.py#L201

**Comment by ceesem** [comment]
I have probably unsubstantiated concerns about "surprise" timestamps, but we already get data back without that sort of metadata and I see the utility of it.

**Comment by bdpedigo** [comment]
can you describe what you mean by surprise? 

p.s. it seems the timestamp is already available to be set if you instantiate a client manually. so I feel this would just be enabling a public way to set it after creation
